# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Wrapper for DMC knockoffs
#'
#' @keywords internal
knockoffDMC_wrapper <- function(X_, pInit_, Q_, n_, p_, K_, seed_) {
    .Call(`_SNPknock_knockoffDMC_wrapper`, X_, pInit_, Q_, n_, p_, K_, seed_)
}

#' Wrapper for HMM knockoffs
#'
#' @keywords internal
knockoffHMM_wrapper <- function(X_, pInit_, Q_, pEmit_, n_, p_, K_, M_, seed_) {
    .Call(`_SNPknock_knockoffHMM_wrapper`, X_, pInit_, Q_, pEmit_, n_, p_, K_, M_, seed_)
}

